services:
  postgres:
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=hatchet
      - POSTGRES_PASSWORD=hatchet
      - POSTGRES_DB=hatchet
    command: postgres -c 'max_connections=1000'
    restart: always
    hostname: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d hatchet -U hatchet"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  rabbitmq:
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "hatchet_rabbitmq_data:/var/lib/rabbitmq"
      - "hatchet_rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  migration:
    environment:
      - DATABASE_URL=postgres://hatchet:hatchet@postgres:5432/hatchet

  setup-config:
    environment:
      - DATABASE_URL=postgres://hatchet:hatchet@postgres:5432/hatchet
      - SERVER_MSGQUEUE_RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - SERVER_AUTH_COOKIE_DOMAIN=localhost:8080
      - SERVER_AUTH_COOKIE_INSECURE=t
      - SERVER_GRPC_BIND_ADDRESS=0.0.0.0
      - SERVER_GRPC_INSECURE=t
      - SERVER_GRPC_BROADCAST_ADDRESS=hatchet-engine:7077
      - SERVER_DEFAULT_ENGINE_VERSION=V1
      - SERVER_INTERNAL_CLIENT_INTERNAL_GRPC_BROADCAST_ADDRESS=hatchet-engine:7070
      - ADMIN_PASSWORD=Admin123!!

  hatchet-engine:
    ports:
      - "7077:7070"
    environment:
      - DATABASE_URL=postgres://hatchet:hatchet@postgres:5432/hatchet
      - SERVER_GRPC_BIND_ADDRESS=0.0.0.0
      - SERVER_GRPC_INSECURE=t
    restart: on-failure

  hatchet-dashboard:
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=postgres://hatchet:hatchet@postgres:5432/hatchet
    restart: on-failure
